title: Modul Bibliotheks- und Archivinformatik (BAIN) / FHGR HS2020
author: Sandra
email: sandra.flueckiger@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch - Modul Bibliotheks- und Archivinformatik (BAIN) / FHGR HS2020

# social links
github_username:  fluecksandra # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
